image: gitlab-registry.cern.ch/linuxsupport/alma9-base:latest

stages:
  - unstagged

include:
  - local: ci/gitlab/normal.yml
    rules:
      - if: $DOCKER_GENERATION != "true"
  - local: ci/gitlab/docker.yml
    rules:
      - if: $DOCKER_GENERATION == "true"

# Empty job, as gitlab-ci requires at least one job
empty:
  stage: unstagged
  script: exit 0
