image: gitlab-registry.cern.ch/linuxsupport/alma9-base:latest

include:
  - local: ci/gitlab/normal.yml
    rules:
      - if: $DOCKER_GENERATION == "true"
        when: never
  - local: ci/gitlab/docker.yml
    rules:
      - if: $DOCKER_GENERATION == "true"

# Empty job, as gitlab-ci requires at least one job
empty:
  script: exit 0
