name: Gitlab Pipeline Integration

on: push

jobs:
  Gitlab_Trigger_Pipeline:
    runs-on: cern:gitlab-ci
    container: ghcr.io/miguensone/github-gitlab-sync:latest
    env:
      GITLAB_URL: ${{ vars.GITLAB_URL }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      COMMIT_REF: ${{ github.sha }}
    outputs:
      job_matrix: ${{ steps.set-matrix.outputs.job_matrix }}
    steps:
      - name: Trigger Gitlab Pipeline
        id: set-matrix
        run: |
          python /opt/bridge/sync-repository.py
          python /opt/bridge/create-temp-branch.py
          export PIPELINE_ID=$(python /opt/bridge/trigger-pipeline.py)
          echo "PIPELINE_ID is set to: ${PIPELINE_ID}"
          echo "PIPELINE_ID=${PIPELINE_ID}" >> $GITHUB_ENV
          export LIST_JOBS=$(python /opt/bridge/retrieve-jobs.py)
          job_matrix=$(echo $LIST_JOBS | tr ',' '\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "job_matrix=$job_matrix" >> $GITHUB_ENV
          echo "job_matrix=$job_matrix" >> $GITHUB_OUTPUT
          echo Jobs detected: $job_matrix

  Gitlab_Pipeline_Jobs:
    needs: Gitlab_Trigger_Pipeline
    runs-on: cern:gitlab-ci
    container: ghcr.io/miguensone/github-gitlab-sync:latest
    env:
      GITLAB_URL: ${{ vars.GITLAB_URL }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    strategy:
      matrix:
        run_id: ${{ fromJson(needs.Gitlab_Trigger_Pipeline.outputs.job_matrix) }}
    steps:
      - name: ${{ matrix.run_id }}
        run: |
          export JOB_ID=${{ matrix.run_id }}
          python /opt/bridge/retrieve-job.py
          echo "JOB_NAME=$(echo Hello_$JOB_ID" >> $GITHUB_ENV
    # steps:
    #   - name: Debug job_matrix
    #     run: echo "job_matrix=${{ needs.Gitlab_Trigger_Pipeline.outputs.job_matrix }}"

  Gitlab_Pipeline_Final_Status:
    needs: [Gitlab_Pipeline_Jobs]
    runs-on: cern:gitlab-ci
    container: ghcr.io/miguensone/github-gitlab-sync:latest
    env:
      GITLAB_URL: ${{ vars.GITLAB_URL }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
      - name: Final Gitlab Pipeline Status
        run: |
          python /opt/bridge/wait-end-pipeline.py
          python /opt/bridge/delete-temp-branch.py
